@url = http://localhost:5223/reservations
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}

###
GET {{url}}/

> {%
    client.global.set(
        "reservationId",
        response.body[0].id
    );
%}

###
GET {{url}}/{{reservationId}}

###
POST {{url}}
Content-Type: application/json

{
  "ParkingSpotId": "{{parkingSpotId}}",
  "EmployeeName": "John Doe",
  "LicensePlate": "XYZ123",
  "Date": "2026-02-07"
}

###
PUT {{url}}/{{reservationId}}
Content-Type: application/json

{
  "LicensePlate": "XYZ124"
}

###
DELETE {{url}}/{{reservationId}}